# Generated by Django 3.2.8 on 2021-10-12 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('affiliations', models.CharField(max_length=256)),
                ('pubcount', models.IntegerField()),
                ('citecount', models.IntegerField()),
                ('hindex', models.IntegerField()),
                ('interests', models.CharField(max_length=512)),
            ],
        ),
    ]
